language: objective-c

env:
    - PROJECT_SCHEME=Simian
    - PROJECT_SCHEME=ROADCore
    - PROJECT_SCHEME=ROADLogger
    - PROJECT_SCHEME=ROADServices
    - PROJECT_SCHEME=ROADWebService
    - PROJECT_SCHEME=ROADObservation
    - PROJECT_SCHEME=ROADSerialization
    - PROJECT_SCHEME=ROADAttributesCodeGenerator

before_script:
    - sudo easy_install cpp-coveralls
    - chmod +x ./script_simian.sh
    - chmod +x ./script_general.sh
    - chmod +x ./coveralls.rb

script:
    - if [[ $PROJECT_SCHEME == Simian ]]; then ./script_simian.sh; else ./script_general.sh; fi

after_success:
    - if [[ $PROJECT_SCHEME != Simian && $PROJECT_SCHEME != ROADAttributesCodeGenerator ]]; then ./coveralls.rb --extension m; fi

notifications:
  email:
    - Nikita_Leonov@epam.com
    - Valery_Demin@epam.com