language: objective-c
env:
    - SPARK_SCHEME=SparkCore
    - SPARK_SCHEME=SparkLogger
    - SPARK_SCHEME=SparkServices
    - SPARK_SCHEME=SparkWebService
    - SPARK_SCHEME=SparkObservation
    - SPARK_SCHEME=SparkSerialization
    - SPARK_SCHEME=SparkAttributesCodeGenerator
before_install:
    - curl -O http://archives.oclint.org/releases/0.7/oclint-0.7-x86_64-apple-darwin-10.tar.gz
    - tar -zxvf oclint-0.7-x86_64-apple-darwin-10.tar.gz
    # =================     Remove necessary rules from "lib/oclint/rules/" folder of oclint     ===========
    #- rm $('pwd')/oclint-0.7-x86_64-apple-darwin-10/lib/oclint/rules/libUnusedMethodParameterRule.dylib
    # ======================================================================================================
    - OCLINT_HOME=$('pwd')/oclint-0.7-x86_64-apple-darwin-10
    - PATH=$OCLINT_HOME/bin:$PATH
before_script:
    # =================     Set environment variables     ===========
    - export WORKSPACE="-workspace Framework/SparkFramework.xcworkspace"
    - export PROJECT="-project tools/SparkAttributesCodeGenerator/SparkAttributesCodeGenerator.xcodeproj"
    - if [[ $SPARK_SCHEME == SparkAttributesCodeGenerator ]]; then export PATCH_FOR_PROJECT_OR_WORKSPACE=$PROJECT; else export PATCH_FOR_PROJECT_OR_WORKSPACE=$WORKSPACE; fi
script:
    - xctool $PATCH_FOR_PROJECT_OR_WORKSPACE -scheme $SPARK_SCHEME -reporter pretty -reporter json-compilation-database:compile_commands.json build
    - if [[ $SPARK_SCHEME != SparkAttributesCodeGenerator ]]; then xctool $WORKSPACE -scheme $SPARK_SCHEME test -sdk iphonesimulator; fi	
    - oclint-json-compilation-database -- -rc=LONG_LINE=300 -rc=LONG_VARIABLE_NAME=50 -max-priority-2 30 -max-priority-3 65
notifications:
  email:
    - Valery_Demin@epam.com